### ISSUE TITLE
The Example Given Doesn't Work

### ISSUE THREAD

**Issue by spiralmedia-tech** [juliangut/slim-routing#8]
Of the used classes:

use Jgut\Slim\Routing\Framework\Strategy\RequestResponse;
use Jgut\Slim\Routing\Response\PayloadResponseType;
use Jgut\Slim\Routing\Response\Handler\JsonResponseHandler;
use Jgut\Slim\Routing\Router;

The first three don't exist and the last one is a blank class!

**Comment by juliangut** [comment]
Hello @spiralmedia-tech, readme file on master does represent current development status, if you're trying to work with any of RC version you should read their respective readme file instead of masters'

That said one thing is wrong indeed, RequestResponse strategy has been removed in latests changes

**Comment by juliangut** [comment]
I've published a new RC with some changes and the examples have been changed as well
